name: axtune
description: "Axtune - A Flutter-based local music player app."
publish_to: 'none'
version: 1.0.0+1

# ---------------------------------------
# Flutter SDK Environment
# ---------------------------------------
environment:
  sdk: ^3.7.2

# ---------------------------------------
# App Dependencies
# ---------------------------------------
dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.4

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # File system and media access
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.3
  media_store_plus: ^0.1.3
  on_audio_query: ^2.9.0
  # flutter_media_metadata: ^1.0.0+1 # optional alternative

  # Audio playback and background service
  just_audio: ^0.9.46
  audio_service: ^0.18.17

  # Splash screen
  flutter_native_splash: ^2.4.5

# ---------------------------------------
# Dev Dependencies
# ---------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  flutter_oss_licenses: ^3.0.4

# ---------------------------------------
# Launcher Icon Configuration
# ---------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

# ---------------------------------------
# Native Splash Configuration
# ---------------------------------------
flutter_native_splash:
  android_gravity: center
  color: "#ffffff"
  image: assets/icons/logo.png
  color_dark: "#000000"
  image_dark: assets/icons/logo.png
  android_12:
    color: "#ffffff"
    image: assets/icons/logo.png
    color_dark: "#000000"
    image_dark: assets/icons/logo.png
  ios: true
  web: false

# ---------------------------------------
# Flutter Configuration
# ---------------------------------------
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/licenses/
    - assets/musics/
    - assets/readme/
